num=int(input("Enter the number you want the table of: "))
print("\n%d's Table: "%num)
print("\n%d X %d = %d"%(num,1,num*1))
print("%d X %d = %d"%(num,2,num*2))
print("%d X %d = %d"%(num,3,num*3))
print("%d X %d = %d"%(num,4,num*4))
print("%d X %d = %d"%(num,5,num*5))
print("%d X %d = %d"%(num,6,num*6))
print("%d X %d = %d"%(num,7,num*7))
print("%d X %d = %d"%(num,8,num*8))
print("%d X %d = %d"%(num,9,num*9))
print("%d X %d = %d"%(num,10,num*10))